Repository grabear/awesome-rshiny, pull requests merged in 2018-03, with the labels that each got.

#66 Add tutorial 'Dynamically Generate Shiny UI'
  README.md
Labels: rShiny Tutorial

#67 Dev master
  CONTRIBUTING.md
  README.md
Labels: rShiny App, rShiny Package, rShiny Tutorial

#68 Added Shiny Apps and A package
  README.md
Labels: rShiny App, rShiny Package
